apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      serviceAccountName: internal-app
      containers:
      - name: app-python
        image: dudukk/devops
        env:
          - name: MY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
        {{- include "app-python.envVars" . | nindent 10 }}
        envFrom:
          - configMapRef:
              name: config
        ports:
        - containerPort: 5000